### ISSUE TITLE
[SUGGESTION] Message to Server ON/OFF

### ISSUE THREAD

**Issue by duhnunes** [rfalias/project_zomboid_bot#1]
Hello,

There are some bots that create counters as if it were a category:
https://i.imgur.com/xPVelwI.png

Your bot could add one of these with "Status: ON(green)/OFF(red)" to identify the PZ server.
And when the server is started (ON), a message in some #channel is sent to alert that the server is on again.

OFF: I can translate if you add a file translation/EN.json (or other extension). if you think about adapting it to other languages, of course.
And thanks you for the bot! (:

**Comment by rfalias** [comment]
I added a scheduled task that will poll the server every 20 seconds and check if it's running. If it is, it will change the bots status to '{survivorcount} survivors online'. If the server is detected as offline, the bot status will change to 'Server offline'

I'll look into having it change some sort of channel name for a status.
