### ISSUE TITLE
Player has died message showing twice

### ISSUE THREAD

**Issue by Rysanlos** [rfalias/project_zomboid_bot#15]
Hello, sorry to bother again.
The fix #14 fixed the disconnected reconnected messages when dying.
BUT
When you die, if you quit without making a new character, it's working fine as it should.
But if you die and you create a new character (respawn), the dying message is showing twice. It's a bit spammy :/
Thanks for your hard work!

**Comment by rfalias** [comment]
I think I corrected this issue in #16 
Give it a try now. Was much better during my testing.

**Comment by Rysanlos** [comment]
It's perfect, working fine as it should, thank you!
