### ISSUE TITLE
pzrestartserver command showing an exception on Windows

### ISSUE THREAD

**Issue by AWL-Gaming** [rfalias/project_zomboid_bot#17]
All rcon and other commands are working except the pzrestartserver.
The server's process name under Windows is java.exe (Zulu) but it seems that the bot is looking for project-zomboid or projectzomboid64 in the title. I could be wrong about this, but here's a traceback log:

```
Ignoring exception in command pzrestartserver:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Z:\Bots\project_zomboid_bot\pzbot.py", line 212, in pzrestartserver
    response = await restart_server(ctx)
  File "Z:\Bots\project_zomboid_bot\pzbot.py", line 145, in restart_server
    p = Popen(c, stdout=subprocess.PIPE)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by rfalias** [comment]
pzrestart calls a linux based systemctl command. 
Let me look into a windows based version. Can you tell me how you stop/start your server on windows?

**Comment by AWL-Gaming** [comment]
> pzrestart calls a linux based systemctl command. Let me look into a windows based version. Can you tell me how you stop/start your server on windows?

Currently we do not have any other way of restarting the server on Windows. Stopping it is by typing "quit" on the console or through an rcon app. Starting up is done manually.

**Comment by rfalias** [comment]
This doc says StartServer64.bat, is that the file you run?
On windows, does it just run with the command window/console open I assume?

**Comment by AWL-Gaming** [comment]
> This doc says StartServer64.bat, is that the file you run? On windows, does it just run with the command window/console open I assume?

Correct, that's the file I use. And yes it shows a window/console when it's running.

**Comment by rfalias** [comment]
Ok, I can look into starting and stopping it from that. 
Can you provide me the output of this, while the server is running:
`wmic PROCESS where "name like '%java%'" get Commandline`

**Comment by AWL-Gaming** [comment]
> Ok, I can look into starting and stopping it from that. Can you provide me the output of this, while the server is running: `wmic PROCESS where "name like '%java%'" get Commandline`

```
java  -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -Dfile.encoding=UTF-8 -Xmx456M -Xms256m -jar launcher.jar                                                                                                                                                                                                                                                                                                                                              
"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -Dfile.encoding=UTF-8 -Xmx456M -Xms256m -jar launcher.jar                                                                                                                                                                                                                                                                                                    
java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -Djline.terminal=jline.UnsupportedTerminal -Dfile.encoding=UTF-8 -Dclient.encoding.override=UTF-8 -Dde.dytanic.cloudnet.wrapper.relocate.io.netty.packagePrefix=de.dytanic.cloudnet.wrapper.relocate. -DIReallyKnowWhatIAmDoingISwear=true -Dcloudnet.wrapper.messages.language=english -Xmx2048M -cp "D:\Game Servers\CloudNet\temp\caches\wrapper.jar" "-javaagent:D:\Game Servers\CloudNet\temp\caches\wrapper.jar" de.dytanic.cloudnet.wrapper.Main io.papermc.paperclip.Main "D:\Game Servers\CloudNet\local\services\Creative-1\paper-1.18.1-101.jar" true nogui
java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -Djline.terminal=jline.UnsupportedTerminal -Dfile.encoding=UTF-8 -Dclient.encoding.override=UTF-8 -Dde.dytanic.cloudnet.wrapper.relocate.io.netty.packagePrefix=de.dytanic.cloudnet.wrapper.relocate. -DIReallyKnowWhatIAmDoingISwear=true -Dcloudnet.wrapper.messages.language=english -Xmx2048M -cp "D:\Game Servers\CloudNet\temp\caches\wrapper.jar" "-javaagent:D:\Game Servers\CloudNet\temp\caches\wrapper.jar" de.dytanic.cloudnet.wrapper.Main io.papermc.paperclip.Main "D:\Game Servers\CloudNet\local\services\Lobby-1\paper-1.18.1-175.jar" true nogui
java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:-UseAdaptiveSizePolicy -XX:CompileThreshold=100 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -Djline.terminal=jline.UnsupportedTerminal -Dfile.encoding=UTF-8 -Dclient.encoding.override=UTF-8 -Dde.dytanic.cloudnet.wrapper.relocate.io.netty.packagePrefix=de.dytanic.cloudnet.wrapper.relocate. -DIReallyKnowWhatIAmDoingISwear=true -Dcloudnet.wrapper.messages.language=english -Xmx256M -cp "D:\Game Servers\CloudNet\temp\caches\wrapper.jar" "-javaagent:D:\Game Servers\CloudNet\temp\caches\wrapper.jar" de.dytanic.cloudnet.wrapper.Main net.md_5.bungee.Bootstrap "D:\Game Servers\CloudNet\local\services\Proxy-1\waterfall-1.18-475.jar" false
"C:\Program Files\Java\jre1.8.0_321\bin\javaw.exe" -Xms512m -Xmx1024m -jar "C:\Users\Administrator\Desktop\DirSyncPro-1.53-Windows\dirsyncpro.jar"                                                                                                                                                                                                                                                                                                                                                                                                            
".\jre64\bin\java.exe"  -Djava.awt.headless=true -Xms8g -Xmx64g -Dzomboid.steam=1 -Dzomboid.znetlog=1 -XX:+UseZGC -XX:-CreateCoredumpOnCrash -XX:-OmitStackTraceInFastThrow -Djava.library.path=natives/;natives/win64/;. -cp java/istack-commons-runtime.jar;java/jassimp.jar;java/javacord-2.0.17-shaded.jar;java/javax.activation-api.jar;java/jaxb-api.jar;java/jaxb-runtime.jar;java/lwjgl.jar;java/lwjgl-natives-windows.jar;java/lwjgl-glfw.jar;java/lwjgl-glfw-natives-windows.jar;java/lwjgl-jemalloc.jar;java/lwjgl-jemalloc-natives-windows.jar;java/lwjgl-opengl.jar;java/lwjgl-opengl-natives-windows.jar;java/lwjgl_util.jar;java/sqlite-jdbc-3.27.2.1.jar;java/trove-3.0.3.jar;java/uncommons-maths-1.2.3.jar;java/ zombie.network.GameServer -statistic 0
```

**Comment by AWL-Gaming** [comment]
We have 3 other servers using the Java sub-processes and another being used by a backup program.

**Comment by rfalias** [comment]
Only one zomboid server correct? I want to make sure I kill the right process :)

**Comment by AWL-Gaming** [comment]
> Only one zomboid server correct? I want to make sure I kill the right process :)

Yes, it's just one server.

**Comment by rfalias** [comment]
Took a bit, but #18 should fix this. 
I will concede that I could do limited testing on this, so I will leave this open until you verify it. 
Basically it will send an rcon save first, since I'm not asking it to close nicely, then kills the java process, then the parent terminal.

**Comment by AWL-Gaming** [comment]
> Took a bit, but #18 should fix this. I will concede that I could do limited testing on this, so I will leave this open until you verify it. Basically it will send an rcon save first, since I'm not asking it to close nicely, then kills the java process, then the parent terminal.

Sorry for the late reply, got an exception when sending the restart command **but it worked**

```
Ignoring exception in command pzrestartserver:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "Z:\Bots\project_zomboid_bot\pzbot.py", line 224, in pzrestartserver
    response = await restart_server(ctx)
  File "Z:\Bots\project_zomboid_bot\pzbot.py", line 160, in restart_server
    return r
UnboundLocalError: local variable 'r' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'r' referenced before assignment
```

Also is it possible that we send a "quit" command instead of "save" since the first one is inclusive and will save the server before gracefully shut it down. It will also prevent the current bug ingame that will reset all safehouses claimed by players if you shutdown the server immediately. Quit is basically save+shutdown.

**Comment by AWL-Gaming** [comment]
Following up with the above, I've modified the save command to "quit" and got the same result. It basically just kills the process instantly before waiting for the graceful save+shutdown done by that command. If there is any way to set a delay before killing the window/process that might solve it all. 10-15s delay should do it.

**Comment by rfalias** [comment]
#19 
I've addressed a few things in this latest merge. 
I issue quit, then wait for rcon to return a timeout indicating the server is basically down. Then it goes through the close/shutdown/restart process. 

I also noticed the rcon path was hard coded, which was not intentional. I added the RCON_PATH variable which defaults to './'

RCON will also now report stderr as well, in the event rcon has some error it will be reported properly.

**Comment by AWL-Gaming** [comment]
> #19 I've addressed a few things in this latest merge. I issue quit, then wait for rcon to return a timeout indicating the server is basically down. Then it goes through the close/shutdown/restart process.
> 
> I also noticed the rcon path was hard coded, which was not intentional. I added the RCON_PATH variable which defaults to './'
> 
> RCON will also now report stderr as well, in the event rcon has some error it will be reported properly.

All is working but now it's not closing down the window. It times out correctly on the RCON bot but it doesn't force close the window after saving.
Also my path is manually set to `SERVER_PATH = os.getenv('SERVER_PATH', "D:/SteamLibrary/steamapps/common/Project Zomboid Dedicated Server")` on the bot's code.
![image](https://user-images.githubusercontent.com/22678541/152212094-9c889480-36e0-42a1-8385-c0ce8a8c8383.png)

**Comment by rfalias** [comment]
I see, the error message on windows for rcon is different for some reason. I modified what it looks for to just find refused. See if #20  works for you

**Comment by AWL-Gaming** [comment]
> I see, the error message on windows for rcon is different for some reason. I modified what it looks for to just find refused. See if #20 works for you

Worked perfectly. It's fixed now thank you!

**Comment by rfalias** [comment]
Great! Thanks for working with me! Glad it's working in windows now.
