### ISSUE TITLE
Feature request: additem command

### ISSUE THREAD

**Issue by AWL-Gaming** [rfalias/project_zomboid_bot#21]
Would be cool if we can give items to players' inventory directly from Discord.
Correct command would be:
additem "username" "module.item", ex : additem "admin" "Base.Axe" 
![image](https://user-images.githubusercontent.com/22678541/152231169-86f647e9-2a32-43db-9bff-9e87a7c51edb.png)
![image](https://user-images.githubusercontent.com/22678541/152231232-c02dd53a-82ae-4854-ba92-d82cb4d5a8a0.png)

**Comment by rfalias** [comment]
Being worked on in #23
