### ISSUE TITLE
Feature Request - Total Time Logged

### ISSUE THREAD

**Issue by AnimeGarlicoin** [rfalias/project_zomboid_bot#25]
I think you could simply calculate the difference between timecodes for connects/disconnects, and add that as additional information to !pzdeaths, but a separate command might work better for some users.

**Comment by rfalias** [comment]
Hey that's a great idea. I'll see if I can get that working.

**Comment by rfalias** [comment]
I added both a standalone playtime command, and a time counter on the deaths report. 
It's parsing logs, so if you remove Zomboid/Logs it will reset the playtime.
I'm also unsure if the logs dir gets removed/cleaned up at any point so YMMV
