### ISSUE TITLE
Death not working properly

### ISSUE THREAD

**Issue by Rysanlos** [rfalias/project_zomboid_bot#8]
Hello, I'm using PZwatcher and PZbot, they are working great, I just have one issue, not important.
When you die, no death message, only "disconnected" and "connected" when we create new character.
Thanks!

**Comment by rfalias** [comment]
Fixed in latest commit. Update pzwatcher.py and restart the service.

**Comment by Rysanlos** [comment]
The deaths message are working great with the new update, but it's still doing disconnected reconnected messages.
I tried this:
```
                if "removed" in l:
                    print("at dc")
                    print(l)
                    user = ls[3].strip('"')
                    await channel.send(f"{user} has disconnected!")
                    break
                if "allowed to join" in l:
                    print("Connected")
                    print(l)
                    user = ls[3].strip('"')
                    await channel.send(f"{user} has joined!")
                    break
                if "died at (" in l:
                    print("At Died")
                    print(l)

                    user = ls[3].strip('"')
                    await channel.send(f"{user} has died!")
                    break
                break

```
Join is working, dying too without disconnected/reconnected, but I can't make disconnecting works.

I tried "removed", "removed connection" and "removed connection index" but nothing works.
Thanks @rfalias
